---
zsh_theme: robbyrussell
zsh_custom_shell_command: "false"
# useful when users are bound to external systems (i.e. active directory)
# zsh_custom_shell_command: "true"
# zsh_default_shell_command: "/opt/pbis/bin/config LoginShellTemplate /usr/bin/zsh"
zsh_aliases:
  # https://opensource.com/article/19/7/bash-aliases
  - ls='ls -F'
  - ll='ls -lh'
  - mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
  - hg='history|grep' # search bash history, I swapped the letters for github-cli compatibility
  - left='ls -t -1' # most recently edited files
  - cg='cd `git rev-parse --show-toplevel`' # go to git main level
ohmyzsh_bundles:
  # Bundles from the default repo (robbyrussell's oh-my-zsh) only need a name
  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
  #
  # `name` is required (any valid file name will do so long as it's unique for the bundles)
  # `url` is git username/repo
  # `version` is git release and is required if `url` is define
  # - name: ansible
  # - name: aws
  # - name: docker
  # - name: docker-compose
  - name: gitfast
  # - name: pipenv
  - name: yarn
  # Syntax highlighting bundle.
  - name: zsh-syntax-highlighting
    git:
      user: zsh-users
      repo: zsh-syntax-highlighting
      version: 0.7.1
  # # Autosuggestions
  # - name: zsh-autosuggestions # `name` is required (any valid file name will do so long as it's unique for the bundles)
  #   repo:
  #     user: zsh-users
  #     repo: zsh-autosuggestions
  #     version: v0.6.4
  - name: powerlevel10k
    skip_zshrc_plugin:
    git:
      user: romkatv
      repo: powerlevel10k
      version: v1.12.0
